/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Homepage;

import Homepage.Forms;
import java.awt.Color;

/**
 *
 * @author santo
 */
public class DeveloperPage extends javax.swing.JFrame {

     Color DefaultColor, ClickedColor;
    
    
    /**
     * Creates new form DeveloperPage
     */
    public DeveloperPage() {
        initComponents();
        ClickedColor = new Color (0,89,102);
        
        DefaultColor = new Color (28,39,54);
        
        forms_pnl.setBackground(DefaultColor);     
        event_pnl.setBackground(DefaultColor);
        PNL_citizeninfo.setBackground(DefaultColor);
        /*health.setBackground(DefaultColor);
        /*formssetBackground(DefaultColor);*/
        
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        event_pnl = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Health_pnl = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        educ_pnl = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        PNL_citizeninfo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        forms_pnl = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        DevHome = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(28, 39, 54));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Swis721 BT", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("HOME");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 510, 110));

        event_pnl.setBackground(new java.awt.Color(28, 39, 54));
        event_pnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        event_pnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                event_pnlMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Swis721 BT", 0, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("EVENTS");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout event_pnlLayout = new javax.swing.GroupLayout(event_pnl);
        event_pnl.setLayout(event_pnlLayout);
        event_pnlLayout.setHorizontalGroup(
            event_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(event_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        event_pnlLayout.setVerticalGroup(
            event_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(event_pnlLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.add(event_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 510, 100));

        Health_pnl.setBackground(new java.awt.Color(28, 39, 54));
        Health_pnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Health_pnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Health_pnlMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Swis721 BT", 0, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("HEALTH");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Health_pnlLayout = new javax.swing.GroupLayout(Health_pnl);
        Health_pnl.setLayout(Health_pnlLayout);
        Health_pnlLayout.setHorizontalGroup(
            Health_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Health_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        Health_pnlLayout.setVerticalGroup(
            Health_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Health_pnlLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel3.add(Health_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 510, 110));

        educ_pnl.setBackground(new java.awt.Color(28, 39, 54));
        educ_pnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        educ_pnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                educ_pnlMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Swis721 BT", 0, 60)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("EDUCATION");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout educ_pnlLayout = new javax.swing.GroupLayout(educ_pnl);
        educ_pnl.setLayout(educ_pnlLayout);
        educ_pnlLayout.setHorizontalGroup(
            educ_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educ_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        educ_pnlLayout.setVerticalGroup(
            educ_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educ_pnlLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel3.add(educ_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 510, -1));

        PNL_citizeninfo.setBackground(new java.awt.Color(28, 39, 54));
        PNL_citizeninfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PNL_citizeninfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PNL_citizeninfoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PNL_citizeninfoMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Swis721 BT", 0, 60)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("CITIZEN INFO");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PNL_citizeninfoLayout = new javax.swing.GroupLayout(PNL_citizeninfo);
        PNL_citizeninfo.setLayout(PNL_citizeninfoLayout);
        PNL_citizeninfoLayout.setHorizontalGroup(
            PNL_citizeninfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_citizeninfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        PNL_citizeninfoLayout.setVerticalGroup(
            PNL_citizeninfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNL_citizeninfoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel3.add(PNL_citizeninfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 510, -1));

        forms_pnl.setBackground(new java.awt.Color(28, 39, 54));
        forms_pnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        forms_pnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                forms_pnlMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Swis721 BT", 0, 60)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("FORMS");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout forms_pnlLayout = new javax.swing.GroupLayout(forms_pnl);
        forms_pnl.setLayout(forms_pnlLayout);
        forms_pnlLayout.setHorizontalGroup(
            forms_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forms_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        forms_pnlLayout.setVerticalGroup(
            forms_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forms_pnlLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel3.add(forms_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 870, 510, -1));

        javax.swing.GroupLayout DevHomeLayout = new javax.swing.GroupLayout(DevHome);
        DevHome.setLayout(DevHomeLayout);
        DevHomeLayout.setHorizontalGroup(
            DevHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1410, Short.MAX_VALUE)
        );
        DevHomeLayout.setVerticalGroup(
            DevHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        jPanel3.add(DevHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 1410, 1080));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DeveloperPage/HOME PAGE.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        CITIZEN_INFO form = new CITIZEN_INFO();
        DevHome.removeAll();
        DevHome.add(form).setVisible(true);
        PNL_citizeninfo.setBackground(ClickedColor);
        forms_pnl.setBackground(DefaultColor);     
        event_pnl.setBackground(DefaultColor);
        educ_pnl.setBackground(DefaultColor);
        Health_pnl.setBackground(DefaultColor);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void PNL_citizeninfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PNL_citizeninfoMouseClicked
        // TODO add your handling code her
              
    }//GEN-LAST:event_PNL_citizeninfoMouseClicked

    private void PNL_citizeninfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PNL_citizeninfoMousePressed
        // TODO add your handling code here:
        PNL_citizeninfo.setBackground(ClickedColor);
        forms_pnl.setBackground(DefaultColor);     
        event_pnl.setBackground(DefaultColor);
        educ_pnl.setBackground(DefaultColor);
        Health_pnl.setBackground(DefaultColor);

        CITIZEN_INFO form = new CITIZEN_INFO();
        DevHome.removeAll();
        DevHome.add(form).setVisible(true);
        

    }//GEN-LAST:event_PNL_citizeninfoMousePressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        EVENT form = new EVENT();
        DevHome.removeAll();
        DevHome.add(form).setVisible(true);
        event_pnl.setBackground(ClickedColor);
        forms_pnl.setBackground(DefaultColor);     
        PNL_citizeninfo.setBackground(DefaultColor);
        educ_pnl.setBackground(DefaultColor);
        Health_pnl.setBackground(DefaultColor);
        
        
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void event_pnlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_event_pnlMousePressed
        // TODO add your handling code here:
        EVENT form = new EVENT();
        DevHome.removeAll();
        DevHome.add(form).setVisible(true);
        event_pnl.setBackground(ClickedColor);
        forms_pnl.setBackground(DefaultColor);     
        PNL_citizeninfo.setBackground(DefaultColor);
        educ_pnl.setBackground(DefaultColor);
        Health_pnl.setBackground(DefaultColor);
        
    }//GEN-LAST:event_event_pnlMousePressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        DeveloperForms form = new DeveloperForms();
        DevHome.removeAll();
        DevHome.add(form).setVisible(true);
        forms_pnl.setBackground(ClickedColor);
        PNL_citizeninfo.setBackground(DefaultColor);
        event_pnl.setBackground(DefaultColor);
        educ_pnl.setBackground(DefaultColor);
        Health_pnl.setBackground(DefaultColor);
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void forms_pnlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forms_pnlMousePressed
        // TODO add your handling code here:
        DeveloperForms form = new DeveloperForms();
        DevHome.removeAll();
        DevHome.add(form).setVisible(true);
        forms_pnl.setBackground(ClickedColor);
        PNL_citizeninfo.setBackground(DefaultColor);
        event_pnl.setBackground(DefaultColor);
        educ_pnl.setBackground(DefaultColor);
        Health_pnl.setBackground(DefaultColor);
        
        
        
        
        
    }//GEN-LAST:event_forms_pnlMousePressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        dev_educ form = new dev_educ();
        DevHome.removeAll();
        DevHome.add(form).setVisible(true);
        educ_pnl.setBackground(ClickedColor);
        forms_pnl.setBackground(DefaultColor);
        PNL_citizeninfo.setBackground(DefaultColor);
        event_pnl.setBackground(DefaultColor);
        Health_pnl.setBackground(DefaultColor);
        
        
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void educ_pnlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_educ_pnlMousePressed
        // TODO add your handling code here:
        dev_educ form = new dev_educ();
        DevHome.removeAll();
        DevHome.add(form).setVisible(true);
        educ_pnl.setBackground(ClickedColor);
        forms_pnl.setBackground(DefaultColor);
        PNL_citizeninfo.setBackground(DefaultColor);
        event_pnl.setBackground(DefaultColor);
        Health_pnl.setBackground(DefaultColor);
        
        
    }//GEN-LAST:event_educ_pnlMousePressed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        dev_health form = new dev_health();
        DevHome.removeAll();
        DevHome.add(form).setVisible(true);
        Health_pnl.setBackground(ClickedColor);
        forms_pnl.setBackground(DefaultColor);
        PNL_citizeninfo.setBackground(DefaultColor);
        event_pnl.setBackground(DefaultColor);
        educ_pnl.setBackground(DefaultColor);
        
        
        
        
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void Health_pnlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Health_pnlMousePressed
        // TODO add your handling code here:
        dev_health form = new dev_health();
        DevHome.removeAll();
        DevHome.add(form).setVisible(true);
        Health_pnl.setBackground(ClickedColor);
        forms_pnl.setBackground(DefaultColor);
        PNL_citizeninfo.setBackground(DefaultColor);
        event_pnl.setBackground(DefaultColor);
        educ_pnl.setBackground(DefaultColor);
        
        
        
        
        
        
    }//GEN-LAST:event_Health_pnlMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeveloperPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeveloperPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeveloperPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeveloperPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeveloperPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DevHome;
    private javax.swing.JPanel Health_pnl;
    private javax.swing.JPanel PNL_citizeninfo;
    private javax.swing.JPanel educ_pnl;
    private javax.swing.JPanel event_pnl;
    private javax.swing.JPanel forms_pnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
