package Homepage;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */



import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author santo
 */
public class Forms extends javax.swing.JInternalFrame {

    /**
     * Creates new form Forms
     */
    public Forms() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        BARANGAY_ID.setVisible(false);
        BARANGAY_INDIGENCY.setVisible(false);
        BARANGAY_CLEARANCE.setVisible(false);
        PROOF_RESIDENCY.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        MAIN = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BARANGAY_ID = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        NAME3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        NAME8 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        NAME10 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        NAME11 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        NAME12 = new javax.swing.JTextField();
        NAME13 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel32 = new javax.swing.JLabel();
        NAME14 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        NAME15 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        NAME17 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        NAME6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jTextArea3 = new javax.swing.JTextArea();
        jTextArea5 = new javax.swing.JTextArea();
        BARANGAY_INDIGENCY = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        NAME1 = new javax.swing.JTextField();
        NAME2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        status_combo = new javax.swing.JComboBox<>();
        NAME4 = new javax.swing.JTextField();
        NAME5 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        BARANGAY_CLEARANCE = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        NAME7 = new javax.swing.JTextField();
        NAME9 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        status_combo1 = new javax.swing.JComboBox<>();
        NAME16 = new javax.swing.JTextField();
        NAME18 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel45 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel46 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        PROOF_RESIDENCY = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        NAME19 = new javax.swing.JTextField();
        NAME20 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        status_combo2 = new javax.swing.JComboBox<>();
        NAME21 = new javax.swing.JTextField();
        NAME22 = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel57 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        status_combo3 = new javax.swing.JComboBox<>();

        setMinimumSize(new java.awt.Dimension(1920, 1240));
        setPreferredSize(new java.awt.Dimension(1920, 1240));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MAIN.setOpaque(false);
        MAIN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(3, 7, 103));
        jLabel3.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 70)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("FORMS ");
        MAIN.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 580, -1));

        jPanel1.setBackground(new java.awt.Color(3, 7, 103));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Swis721 BT", 0, 60)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("PROOF OF RESIDENCY");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 780, 50));

        MAIN.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 900, 760, 170));

        jPanel2.setBackground(new java.awt.Color(3, 7, 103));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Swis721 BT", 0, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("BARANGAY ID");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 520, 50));

        MAIN.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 230, 760, 170));

        jPanel3.setBackground(new java.awt.Color(3, 7, 103));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Swis721 BT", 0, 60)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("BARANGAY INDIGENCY");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 780, 50));

        MAIN.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 450, 760, 170));

        jPanel4.setBackground(new java.awt.Color(3, 7, 103));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Swis721 BT", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("BARANGAY CLEARANCE");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 780, 50));

        MAIN.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 670, 760, 170));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage/form na ui.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        MAIN.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1956, -1));

        jLabel6.setFont(new java.awt.Font("Swis721 BT", 0, 60)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("BARANGAY CLEARANCE");
        MAIN.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 780, 50));

        getContentPane().add(MAIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1210));

        BARANGAY_ID.setBackground(new java.awt.Color(255, 255, 255));
        BARANGAY_ID.setMinimumSize(new java.awt.Dimension(1910, 1240));
        BARANGAY_ID.setPreferredSize(new java.awt.Dimension(1920, 1240));
        BARANGAY_ID.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel19.setText("(House/Building No. - Street - Barangay - Munincipality/City -Province)");
        BARANGAY_ID.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 380, 30));

        NAME3.setBackground(new java.awt.Color(153, 204, 255));
        NAME3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME3ActionPerformed(evt);
            }
        });
        BARANGAY_ID.add(NAME3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, 570, 60));

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("GENDER :");
        BARANGAY_ID.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 210, 30));

        jLabel21.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("NAME :");
        BARANGAY_ID.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 150, 30));

        jLabel22.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("OCCUPATION :");
        BARANGAY_ID.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 300, 30));

        jLabel23.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel23.setText("ADRESS:");
        BARANGAY_ID.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 230, 30));

        NAME8.setBackground(new java.awt.Color(153, 204, 255));
        NAME8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME8ActionPerformed(evt);
            }
        });
        BARANGAY_ID.add(NAME8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 170, 270, 40));

        jPanel10.setBackground(new java.awt.Color(3, 7, 103));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(0, 0, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(51, 51, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1910, 160));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1910, 270));

        BARANGAY_ID.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1110, 1910, 300));

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setFont(new java.awt.Font("Swis721 BT", 1, 60)); // NOI18N
        jButton2.setForeground(new java.awt.Color(3, 7, 103));
        jButton2.setText("SUBMIT");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        BARANGAY_ID.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 930, 520, 130));

        jLabel24.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 60)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(3, 7, 103));
        jLabel24.setText("REQUEST OF BARANGAY ID");
        BARANGAY_ID.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        jLabel26.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("SUFFIX");
        BARANGAY_ID.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 140, 100, 30));

        NAME10.setBackground(new java.awt.Color(153, 204, 255));
        NAME10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME10ActionPerformed(evt);
            }
        });
        BARANGAY_ID.add(NAME10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 270, 40));

        jLabel28.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("LAST NAME :");
        BARANGAY_ID.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 100, 30));

        NAME11.setBackground(new java.awt.Color(153, 204, 255));
        NAME11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME11ActionPerformed(evt);
            }
        });
        BARANGAY_ID.add(NAME11, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 270, 40));

        jLabel30.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("MIDDLE  NAME");
        BARANGAY_ID.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 100, 30));

        NAME12.setBackground(new java.awt.Color(153, 204, 255));
        NAME12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME12ActionPerformed(evt);
            }
        });
        BARANGAY_ID.add(NAME12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 270, 40));

        NAME13.setBackground(new java.awt.Color(153, 204, 255));
        NAME13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME13ActionPerformed(evt);
            }
        });
        BARANGAY_ID.add(NAME13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 270, 40));

        jLabel31.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setText("SOCIAL MEDIA:");
        BARANGAY_ID.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 340, 260, 30));
        BARANGAY_ID.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, 270, 40));

        jLabel32.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel32.setText("VALID ID:");
        BARANGAY_ID.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, 200, 30));

        NAME14.setBackground(new java.awt.Color(153, 204, 255));
        NAME14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME14ActionPerformed(evt);
            }
        });
        BARANGAY_ID.add(NAME14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 370, 270, 40));

        jLabel33.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel33.setText("( Munincipality/City -Province)");
        BARANGAY_ID.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 380, 30));

        NAME15.setBackground(new java.awt.Color(153, 204, 255));
        NAME15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME15ActionPerformed(evt);
            }
        });
        BARANGAY_ID.add(NAME15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 270, 40));

        jLabel34.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel34.setText("AGE :");
        BARANGAY_ID.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 150, 30));

        jLabel35.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel35.setText("FIRST NAME");
        BARANGAY_ID.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 100, 30));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jRadioButton1.setText("MALE");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        BARANGAY_ID.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jRadioButton2.setText("FEMALE");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        BARANGAY_ID.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));

        jLabel29.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("BIRTHDATE");
        BARANGAY_ID.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 210, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BARANGAY_ID.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 270, 270, 40));

        jLabel36.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel36.setText("NATIONALITY");
        BARANGAY_ID.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 210, 30));

        NAME17.setBackground(new java.awt.Color(153, 204, 255));
        NAME17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME17ActionPerformed(evt);
            }
        });
        BARANGAY_ID.add(NAME17, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 270, 40));

        jLabel37.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel37.setText("PHONE NUMBER");
        BARANGAY_ID.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 260, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BARANGAY_ID.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 260, 40));

        jLabel38.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel38.setText("BIRTHPLACE :");
        BARANGAY_ID.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 230, 30));

        NAME6.setBackground(new java.awt.Color(153, 204, 255));
        NAME6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME6ActionPerformed(evt);
            }
        });
        BARANGAY_ID.add(NAME6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 560, 60));

        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(3, 7, 103), 2));
        BARANGAY_ID.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 620, 300, 300));

        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(3, 7, 103), 2, true));
        BARANGAY_ID.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 630, 600, 360));

        jButton7.setBackground(new java.awt.Color(3, 7, 103));
        jButton7.setText("UPLOAD IMAGE");
        BARANGAY_ID.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 1020, 600, 40));

        jLabel63.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel63.setText("CIVIL STATUS:");
        BARANGAY_ID.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 240, 200, 30));

        jLabel64.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel64.setText("2x2 PICTURE: ");
        BARANGAY_ID.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 590, 200, 30));

        jLabel65.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel65.setText("(UMID, VOTER'S ID, DRIVER'S LICENSE, SCHOOL ID, BARANGAY ID)");
        BARANGAY_ID.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 340, 30));

        jButton8.setBackground(new java.awt.Color(3, 7, 103));
        jButton8.setText("UPLOAD IMAGE");
        BARANGAY_ID.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 950, 300, 40));

        jPanel9.setBackground(new java.awt.Color(3, 7, 104));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea3.setBackground(new java.awt.Color(3, 7, 103));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setTabSize(4);
        jTextArea3.setText("1.Mag-fill out ng form online\n\tIlagay ang: pangalan, address, edad, trabaho, \t\tcontact number, atbp.\n2.I-upload ang 2x2 ID picture\n3.I-submit ang form\n\tAuto-validate kung kumpleto ang \t\t\timpormasyon\n4.Makakatanggap ng resibo o reference slip\n\tMay Reference Number, pangalan, at petsa ng \t\trequest\n5.Pumunta sa barangay dala ang resibo\n\tPara ma-verify at ma-claim ang Barangay ID");
        jTextArea3.setWrapStyleWord(true);
        jTextArea3.setBorder(null);
        jPanel9.add(jTextArea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 490, 430));

        jTextArea5.setBackground(new java.awt.Color(3, 7, 103));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        jTextArea5.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea5.setLineWrap(true);
        jTextArea5.setRows(5);
        jTextArea5.setText("STEPS PARA KUMUHA NG BARANGAY ID GAMIT ANG INFORMATION SYSTEM\n\n");
        jTextArea5.setWrapStyleWord(true);
        jTextArea5.setBorder(null);
        jPanel9.add(jTextArea5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 490, 150));

        BARANGAY_ID.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 170, 520, 700));

        getContentPane().add(BARANGAY_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1240));

        BARANGAY_INDIGENCY.setBackground(new java.awt.Color(255, 255, 255));
        BARANGAY_INDIGENCY.setMinimumSize(new java.awt.Dimension(1910, 1240));
        BARANGAY_INDIGENCY.setPreferredSize(new java.awt.Dimension(1920, 1240));
        BARANGAY_INDIGENCY.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel11.setText("(House/Building No. - Street - Barangay - Munincipality/City -Province)");
        BARANGAY_INDIGENCY.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 380, 30));

        NAME1.setBackground(new java.awt.Color(153, 204, 255));
        NAME1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME1ActionPerformed(evt);
            }
        });
        BARANGAY_INDIGENCY.add(NAME1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 950, 60));

        NAME2.setBackground(new java.awt.Color(153, 204, 255));
        NAME2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME2ActionPerformed(evt);
            }
        });
        BARANGAY_INDIGENCY.add(NAME2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 420, 60));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel12.setText("STATUS:");
        BARANGAY_INDIGENCY.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 220, 30));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel13.setText("NAME :");
        BARANGAY_INDIGENCY.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 150, 30));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel14.setText("AGE :");
        BARANGAY_INDIGENCY.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 150, 30));

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel15.setText("ADRESS : ");
        BARANGAY_INDIGENCY.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 150, 30));

        status_combo.setBackground(new java.awt.Color(153, 204, 255));
        status_combo.setForeground(new java.awt.Color(153, 204, 255));
        status_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        status_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status_comboActionPerformed(evt);
            }
        });
        BARANGAY_INDIGENCY.add(status_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 420, 60));

        NAME4.setBackground(new java.awt.Color(153, 204, 255));
        NAME4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME4ActionPerformed(evt);
            }
        });
        BARANGAY_INDIGENCY.add(NAME4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 420, 60));

        NAME5.setBackground(new java.awt.Color(153, 204, 255));
        NAME5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME5ActionPerformed(evt);
            }
        });
        BARANGAY_INDIGENCY.add(NAME5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 420, 60));

        jPanel6.setBackground(new java.awt.Color(3, 7, 103));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setBackground(new java.awt.Color(3, 7, 103));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("STEPS PARA KUMUHA NG BARANGAY CERTIFICATE OF INDIGENCY GAMIT ANG INFORMATION SYSTEM\n\n");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jPanel6.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 700, 150));

        jTextArea2.setBackground(new java.awt.Color(3, 7, 103));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setTabSize(4);
        jTextArea2.setText("1. Fill Out Form\n\tIlagay ang personal na impormasyon at layunin ng \t\tpagkuha.\n2. Review Details\n\tSuriin ang mga impormasyon bago isubmit.\n3. Submit Request\n\tI-click ang \"Submit\" para maipadala ang request sa \tbarangay.\n4. Receive Receipt\n\tMakakatanggap ng resibo o  para sa pag-claim.\n5. Claim at Barangay\n\tDalhin ang resibo sa barangay hall para kunin ang \t\tcertificate.");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setBorder(null);
        jPanel6.add(jTextArea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 640, -1));

        BARANGAY_INDIGENCY.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 120, 710, 740));

        jPanel7.setBackground(new java.awt.Color(3, 7, 103));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(51, 51, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1910, 160));

        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1910, 270));

        BARANGAY_INDIGENCY.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 950, 1910, 300));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Swis721 BT", 1, 60)); // NOI18N
        jButton1.setForeground(new java.awt.Color(3, 7, 103));
        jButton1.setText("SUBMIT");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        BARANGAY_INDIGENCY.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 730, 950, 130));

        jLabel16.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 60)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(3, 7, 103));
        jLabel16.setText("REQUEST BARANGAY INDIGENCY");
        BARANGAY_INDIGENCY.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel17.setText("PURPOSE :");
        BARANGAY_INDIGENCY.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 150, 30));

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel18.setText("(EDUCATIONAL ASSISTANCE, HEALTH ASSISTANCE,atbp)");
        BARANGAY_INDIGENCY.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 340, 30));

        getContentPane().add(BARANGAY_INDIGENCY, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1240));

        BARANGAY_CLEARANCE.setBackground(new java.awt.Color(255, 255, 255));
        BARANGAY_CLEARANCE.setMinimumSize(new java.awt.Dimension(1910, 1240));
        BARANGAY_CLEARANCE.setPreferredSize(new java.awt.Dimension(1920, 1240));
        BARANGAY_CLEARANCE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel25.setText("(House/Building No. - Street - Barangay - Munincipality/City -Province)");
        BARANGAY_CLEARANCE.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, 380, 30));

        NAME7.setBackground(new java.awt.Color(153, 204, 255));
        NAME7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME7ActionPerformed(evt);
            }
        });
        BARANGAY_CLEARANCE.add(NAME7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 660, 950, 60));

        NAME9.setBackground(new java.awt.Color(153, 204, 255));
        NAME9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME9ActionPerformed(evt);
            }
        });
        BARANGAY_CLEARANCE.add(NAME9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 420, 60));

        jLabel27.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel27.setText("BIRTHDATE :");
        BARANGAY_CLEARANCE.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 220, 30));

        jLabel39.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel39.setText("NAME :");
        BARANGAY_CLEARANCE.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 150, 30));

        jLabel40.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel40.setText("VALID ID :");
        BARANGAY_CLEARANCE.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 190, 150, 30));

        jLabel41.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel41.setText("ADRESS : ");
        BARANGAY_CLEARANCE.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 150, 30));

        status_combo1.setBackground(new java.awt.Color(153, 204, 255));
        status_combo1.setForeground(new java.awt.Color(153, 204, 255));
        status_combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        status_combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status_combo1ActionPerformed(evt);
            }
        });
        BARANGAY_CLEARANCE.add(status_combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 420, 60));

        NAME16.setBackground(new java.awt.Color(153, 204, 255));
        NAME16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME16ActionPerformed(evt);
            }
        });
        BARANGAY_CLEARANCE.add(NAME16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 420, 60));

        NAME18.setBackground(new java.awt.Color(153, 204, 255));
        NAME18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME18ActionPerformed(evt);
            }
        });
        BARANGAY_CLEARANCE.add(NAME18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 420, 60));

        jPanel13.setBackground(new java.awt.Color(3, 7, 103));
        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(0, 0, 204));
        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(51, 51, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1910, 160));

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1910, 270));

        BARANGAY_CLEARANCE.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1060, 1910, 300));

        jButton3.setBackground(new java.awt.Color(3, 7, 103));
        jButton3.setFont(new java.awt.Font("Swis721 BT", 1, 75)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SUBMIT");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        BARANGAY_CLEARANCE.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 820, 1670, 130));

        jLabel42.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 60)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(3, 7, 103));
        jLabel42.setText("REQUEST BARANGAY CLEARANCE");
        BARANGAY_CLEARANCE.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel43.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel43.setText("PURPOSE :");
        BARANGAY_CLEARANCE.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 150, 30));

        jLabel44.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel44.setText("(UMID, VOTER'S ID, DRIVER'S LICENSE, SCHOOL ID, BARANGAY ID)");
        BARANGAY_CLEARANCE.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 210, 340, 30));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jRadioButton3.setText("MALE");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        BARANGAY_CLEARANCE.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jRadioButton4.setText("FEMALE");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        BARANGAY_CLEARANCE.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, -1, -1));

        jLabel45.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel45.setText("GENDER :");
        BARANGAY_CLEARANCE.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 210, -1));

        jDateChooser2.setBackground(new java.awt.Color(153, 204, 255));
        BARANGAY_CLEARANCE.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 410, 60));

        jLabel46.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel46.setText("CIVIL STATUS:");
        BARANGAY_CLEARANCE.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 220, 30));

        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(3, 7, 103), 2, true));
        BARANGAY_CLEARANCE.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 250, 600, 360));

        jButton4.setBackground(new java.awt.Color(3, 7, 103));
        jButton4.setFont(new java.awt.Font("Swis721 BT", 0, 35)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("UPLOAD IMAGE");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        BARANGAY_CLEARANCE.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 650, 600, 70));

        jLabel47.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel47.setText("AGE :");
        BARANGAY_CLEARANCE.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 150, 30));

        jLabel48.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel48.setText("(EDUCATIONAL ASSISTANCE, HEALTH ASSISTANCE,atbp)");
        BARANGAY_CLEARANCE.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 340, 30));

        getContentPane().add(BARANGAY_CLEARANCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1240));

        PROOF_RESIDENCY.setBackground(new java.awt.Color(255, 255, 255));
        PROOF_RESIDENCY.setMinimumSize(new java.awt.Dimension(1910, 1240));
        PROOF_RESIDENCY.setPreferredSize(new java.awt.Dimension(1920, 1240));
        PROOF_RESIDENCY.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel49.setText("(House/Building No. - Street - Barangay - Munincipality/City -Province)");
        PROOF_RESIDENCY.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, 380, 30));

        NAME19.setBackground(new java.awt.Color(153, 204, 255));
        NAME19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME19ActionPerformed(evt);
            }
        });
        PROOF_RESIDENCY.add(NAME19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 660, 950, 60));

        NAME20.setBackground(new java.awt.Color(153, 204, 255));
        NAME20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME20ActionPerformed(evt);
            }
        });
        PROOF_RESIDENCY.add(NAME20, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 420, 60));

        jLabel50.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel50.setText("BIRTHDATE :");
        PROOF_RESIDENCY.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 220, 30));

        jLabel51.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel51.setText("NAME :");
        PROOF_RESIDENCY.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 150, 30));

        jLabel52.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel52.setText("VALID ID :");
        PROOF_RESIDENCY.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 190, 150, 30));

        jLabel53.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel53.setText("TAGAL NG PANINIRAHAN: ");
        PROOF_RESIDENCY.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 750, 370, 30));

        status_combo2.setBackground(new java.awt.Color(153, 204, 255));
        status_combo2.setForeground(new java.awt.Color(153, 204, 255));
        status_combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        status_combo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status_combo2ActionPerformed(evt);
            }
        });
        PROOF_RESIDENCY.add(status_combo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 780, 950, 60));

        NAME21.setBackground(new java.awt.Color(153, 204, 255));
        NAME21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME21ActionPerformed(evt);
            }
        });
        PROOF_RESIDENCY.add(NAME21, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 420, 60));

        NAME22.setBackground(new java.awt.Color(153, 204, 255));
        NAME22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAME22ActionPerformed(evt);
            }
        });
        PROOF_RESIDENCY.add(NAME22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 420, 60));

        jPanel16.setBackground(new java.awt.Color(3, 7, 103));
        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(0, 0, 204));
        jPanel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBackground(new java.awt.Color(51, 51, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1910, 160));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1910, 270));

        PROOF_RESIDENCY.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1060, 1910, 300));

        jButton5.setBackground(new java.awt.Color(3, 7, 103));
        jButton5.setFont(new java.awt.Font("Swis721 BT", 1, 75)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("SUBMIT");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        PROOF_RESIDENCY.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 890, 1670, 130));

        jLabel54.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 60)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(3, 7, 103));
        jLabel54.setText("REQUEST PROOF OF RESIDENCY");
        PROOF_RESIDENCY.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel55.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel55.setText("PURPOSE :");
        PROOF_RESIDENCY.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 150, 30));

        jLabel56.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel56.setText("(UMID, VOTER'S ID, DRIVER'S LICENSE, SCHOOL ID, BARANGAY ID)");
        PROOF_RESIDENCY.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 210, 340, 30));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jRadioButton5.setText("MALE");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        PROOF_RESIDENCY.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jRadioButton6.setText("FEMALE");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        PROOF_RESIDENCY.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, -1, -1));

        jLabel57.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel57.setText("GENDER :");
        PROOF_RESIDENCY.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 210, -1));

        jDateChooser3.setBackground(new java.awt.Color(153, 204, 255));
        PROOF_RESIDENCY.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 410, 60));

        jLabel58.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel58.setText("CIVIL STATUS:");
        PROOF_RESIDENCY.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 220, 30));

        jLabel59.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(3, 7, 103), 2, true));
        PROOF_RESIDENCY.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 250, 600, 360));

        jButton6.setBackground(new java.awt.Color(3, 7, 103));
        jButton6.setFont(new java.awt.Font("Swis721 BT", 0, 35)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("UPLOAD IMAGE");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        PROOF_RESIDENCY.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 650, 600, 70));

        jLabel60.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel60.setText("AGE :");
        PROOF_RESIDENCY.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 150, 30));

        jLabel61.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel61.setText("(EDUCATIONAL ASSISTANCE, HEALTH ASSISTANCE,atbp)");
        PROOF_RESIDENCY.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 340, 30));

        jLabel62.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel62.setText("ADRESS : ");
        PROOF_RESIDENCY.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, 150, 30));

        status_combo3.setBackground(new java.awt.Color(153, 204, 255));
        status_combo3.setForeground(new java.awt.Color(153, 204, 255));
        status_combo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        status_combo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status_combo3ActionPerformed(evt);
            }
        });
        PROOF_RESIDENCY.add(status_combo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 420, 60));

        getContentPane().add(PROOF_RESIDENCY, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NAME1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME1ActionPerformed

    private void NAME2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME2ActionPerformed

    private void NAME4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME4ActionPerformed

    private void NAME5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME5ActionPerformed

    private void status_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status_comboActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        BARANGAY_ID.setVisible(true);
        MAIN.setVisible(false);
        
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        BARANGAY_ID.setVisible(true);
        MAIN.setVisible(false);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void NAME8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME8ActionPerformed

    private void NAME3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME3ActionPerformed

    private void NAME10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME10ActionPerformed

    private void NAME11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME11ActionPerformed

    private void NAME12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME12ActionPerformed

    private void NAME13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME13ActionPerformed

    private void NAME14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME14ActionPerformed

    private void NAME15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME15ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void NAME17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME17ActionPerformed

    private void NAME6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME6ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        BARANGAY_INDIGENCY.setVisible(true);
        MAIN.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        BARANGAY_INDIGENCY.setVisible(true);
        MAIN.setVisible(false);
        
    }//GEN-LAST:event_jPanel3MouseClicked

    private void NAME7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME7ActionPerformed

    private void NAME9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME9ActionPerformed

    private void status_combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status_combo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status_combo1ActionPerformed

    private void NAME16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME16ActionPerformed

    private void NAME18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME18ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        BARANGAY_CLEARANCE.setVisible(true);
        MAIN.setVisible(false);
        
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        BARANGAY_CLEARANCE.setVisible(true);
        MAIN.setVisible(false);
        
    }//GEN-LAST:event_jPanel4MouseClicked

    private void NAME19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME19ActionPerformed

    private void NAME20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME20ActionPerformed

    private void status_combo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status_combo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status_combo2ActionPerformed

    private void NAME21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME21ActionPerformed

    private void NAME22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAME22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAME22ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void status_combo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status_combo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status_combo3ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        PROOF_RESIDENCY.setVisible(true);
        MAIN.setVisible(false);
        
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        PROOF_RESIDENCY.setVisible(true);
        MAIN.setVisible(false);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BARANGAY_CLEARANCE;
    private javax.swing.JPanel BARANGAY_ID;
    private javax.swing.JPanel BARANGAY_INDIGENCY;
    private javax.swing.JPanel MAIN;
    private javax.swing.JTextField NAME1;
    private javax.swing.JTextField NAME10;
    private javax.swing.JTextField NAME11;
    private javax.swing.JTextField NAME12;
    private javax.swing.JTextField NAME13;
    private javax.swing.JTextField NAME14;
    private javax.swing.JTextField NAME15;
    private javax.swing.JTextField NAME16;
    private javax.swing.JTextField NAME17;
    private javax.swing.JTextField NAME18;
    private javax.swing.JTextField NAME19;
    private javax.swing.JTextField NAME2;
    private javax.swing.JTextField NAME20;
    private javax.swing.JTextField NAME21;
    private javax.swing.JTextField NAME22;
    private javax.swing.JTextField NAME3;
    private javax.swing.JTextField NAME4;
    private javax.swing.JTextField NAME5;
    private javax.swing.JTextField NAME6;
    private javax.swing.JTextField NAME7;
    private javax.swing.JTextField NAME8;
    private javax.swing.JTextField NAME9;
    private javax.swing.JPanel PROOF_RESIDENCY;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JComboBox<String> status_combo;
    private javax.swing.JComboBox<String> status_combo1;
    private javax.swing.JComboBox<String> status_combo2;
    private javax.swing.JComboBox<String> status_combo3;
    // End of variables declaration//GEN-END:variables
}
