/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package DeveloperPage;

import java.awt.Color;
import javax.swing.BorderFactory;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JPanel;
import javax.swing.JLabel;

/**
 *
 * @author santo
 */
public class EVENT extends javax.swing.JInternalFrame {

    String pathImageId = null ;
    
    
    
    /**
     * Creates new form EVENT
     */
    boolean Panel1 = false;
    boolean Panel2 = false ;
    boolean Panel3 = false ;
    boolean Panel4= false ;
    boolean Panel5= false ;
    boolean Panel6 = false ;
    
    
    int index = 0;
    int clickCount = 0;
    int selectedIndex = -1;
    int[] eventIds = new int[3];
    
    
    public EVENT() {
        initComponents();
        ADD_event.setVisible(false);
        Panelremove1.setVisible(false);
        Panelremove2.setVisible(false);
        Panelremove3.setVisible(false);
        Past_event1.setVisible(false);
        Past_event2.setVisible(false);
        Past_event3.setVisible(false);
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ADD_event = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        event_pnl = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CaptiontoGet = new javax.swing.JTextArea();
        Add_image_BTN = new javax.swing.JLabel();
        MAIN = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Panelremove1 = new javax.swing.JPanel();
        announce_1 = new javax.swing.JLabel();
        Panelremove2 = new javax.swing.JPanel();
        announce_2 = new javax.swing.JLabel();
        Panelremove3 = new javax.swing.JPanel();
        announce_3 = new javax.swing.JLabel();
        Past_event1 = new javax.swing.JPanel();
        Past_announce1 = new javax.swing.JLabel();
        Past_event2 = new javax.swing.JPanel();
        Past_announce2 = new javax.swing.JLabel();
        Past_event3 = new javax.swing.JPanel();
        Past_announce3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        add_pnlbtn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        add_desktop = new javax.swing.JDesktopPane();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ADD_event.setBackground(new java.awt.Color(255, 255, 255));
        ADD_event.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(3, 7, 103));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DeveloperPage/poblacion logo finals na talaga.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Candara", 1, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BARANGAY POBLACION, BUSTOS, BULACAN");

        jLabel7.setFont(new java.awt.Font("Candara Light", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("INFORMATION SYSTEM");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DeveloperPage/BUSTOS BULACAN LOGO 130.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(20, 20, 20)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(210, 210, 210)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(27, 27, 27)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel6)
                            .addGap(11, 11, 11)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel8))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ADD_event.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1400, 140));

        event_pnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(3, 7, 103), 2));
        event_pnl.setPreferredSize(new java.awt.Dimension(960, 540));
        ADD_event.add(event_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 960, 540));

        jButton2.setBackground(new java.awt.Color(102, 153, 255));
        jButton2.setFont(new java.awt.Font("Swis721 BT", 1, 48)); // NOI18N
        jButton2.setForeground(new java.awt.Color(3, 7, 103));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DeveloperPage/addeventicon64.png"))); // NOI18N
        jButton2.setText("ADD");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        ADD_event.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 890, 510, 110));

        jPanel4.setBackground(new java.awt.Color(3, 7, 103));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 45)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CAPTION");

        CaptiontoGet.setColumns(20);
        CaptiontoGet.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CaptiontoGet.setRows(5);
        jScrollPane1.setViewportView(CaptiontoGet);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel4)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        ADD_event.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 180, 330, 640));

        Add_image_BTN.setFont(new java.awt.Font("Swis721 BT", 0, 36)); // NOI18N
        Add_image_BTN.setForeground(new java.awt.Color(3, 7, 103));
        Add_image_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DeveloperPage/addimage64.png"))); // NOI18N
        Add_image_BTN.setText("Add Image");
        Add_image_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_image_BTNMouseClicked(evt);
            }
        });
        ADD_event.add(Add_image_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 740, -1, -1));

        getContentPane().add(ADD_event, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 1050));

        MAIN.setOpaque(false);
        MAIN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 45)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DeveloperPage/announcementicon64.png"))); // NOI18N
        jLabel2.setText("ANNOUNCEMENTS");
        MAIN.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 51, -1, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 45)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DeveloperPage/pastevent64.png"))); // NOI18N
        jLabel3.setText("PAST EVENTS");
        MAIN.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, -1, -1));

        Panelremove1.setBackground(new java.awt.Color(3, 7, 103));
        Panelremove1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panelremove1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panelremove1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panelremove1MouseClicked(evt);
            }
        });

        announce_1.setFont(new java.awt.Font("Candara", 1, 40)); // NOI18N
        announce_1.setForeground(new java.awt.Color(255, 255, 255));
        announce_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout Panelremove1Layout = new javax.swing.GroupLayout(Panelremove1);
        Panelremove1.setLayout(Panelremove1Layout);
        Panelremove1Layout.setHorizontalGroup(
            Panelremove1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(announce_1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );
        Panelremove1Layout.setVerticalGroup(
            Panelremove1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panelremove1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(announce_1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        MAIN.add(Panelremove1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 500, 140));

        Panelremove2.setBackground(new java.awt.Color(3, 7, 103));
        Panelremove2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panelremove2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panelremove2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panelremove2MouseClicked(evt);
            }
        });

        announce_2.setFont(new java.awt.Font("Candara", 1, 40)); // NOI18N
        announce_2.setForeground(new java.awt.Color(255, 255, 255));
        announce_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout Panelremove2Layout = new javax.swing.GroupLayout(Panelremove2);
        Panelremove2.setLayout(Panelremove2Layout);
        Panelremove2Layout.setHorizontalGroup(
            Panelremove2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(announce_2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        Panelremove2Layout.setVerticalGroup(
            Panelremove2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panelremove2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(announce_2, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        MAIN.add(Panelremove2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        Panelremove3.setBackground(new java.awt.Color(3, 7, 103));
        Panelremove3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Panelremove3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panelremove3MouseClicked(evt);
            }
        });

        announce_3.setFont(new java.awt.Font("Candara", 1, 40)); // NOI18N
        announce_3.setForeground(new java.awt.Color(255, 255, 255));
        announce_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        announce_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout Panelremove3Layout = new javax.swing.GroupLayout(Panelremove3);
        Panelremove3.setLayout(Panelremove3Layout);
        Panelremove3Layout.setHorizontalGroup(
            Panelremove3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(announce_3, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
        Panelremove3Layout.setVerticalGroup(
            Panelremove3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panelremove3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(announce_3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        MAIN.add(Panelremove3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, -1, -1));

        Past_event1.setBackground(new java.awt.Color(3, 7, 103));
        Past_event1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Past_event1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Past_event1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Past_event1MouseClicked(evt);
            }
        });

        Past_announce1.setFont(new java.awt.Font("Candara", 1, 40)); // NOI18N
        Past_announce1.setForeground(new java.awt.Color(255, 255, 255));
        Past_announce1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout Past_event1Layout = new javax.swing.GroupLayout(Past_event1);
        Past_event1.setLayout(Past_event1Layout);
        Past_event1Layout.setHorizontalGroup(
            Past_event1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Past_announce1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        Past_event1Layout.setVerticalGroup(
            Past_event1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Past_event1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Past_announce1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        MAIN.add(Past_event1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, -1, -1));

        Past_event2.setBackground(new java.awt.Color(3, 7, 103));
        Past_event2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Past_event2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Past_event2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Past_event2MouseClicked(evt);
            }
        });

        Past_announce2.setFont(new java.awt.Font("Candara", 1, 40)); // NOI18N
        Past_announce2.setForeground(new java.awt.Color(255, 255, 255));
        Past_announce2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout Past_event2Layout = new javax.swing.GroupLayout(Past_event2);
        Past_event2.setLayout(Past_event2Layout);
        Past_event2Layout.setHorizontalGroup(
            Past_event2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Past_announce2, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );
        Past_event2Layout.setVerticalGroup(
            Past_event2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Past_event2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Past_announce2, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        MAIN.add(Past_event2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, -1, -1));

        Past_event3.setBackground(new java.awt.Color(3, 7, 103));
        Past_event3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Past_event3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Past_event3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Past_event3MouseClicked(evt);
            }
        });

        Past_announce3.setFont(new java.awt.Font("Candara", 1, 40)); // NOI18N
        Past_announce3.setForeground(new java.awt.Color(255, 255, 255));
        Past_announce3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout Past_event3Layout = new javax.swing.GroupLayout(Past_event3);
        Past_event3.setLayout(Past_event3Layout);
        Past_event3Layout.setHorizontalGroup(
            Past_event3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Past_announce3, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );
        Past_event3Layout.setVerticalGroup(
            Past_event3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Past_event3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Past_announce3, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        MAIN.add(Past_event3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 600, -1, -1));

        jPanel3.setBackground(new java.awt.Color(3, 7, 103));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_pnlbtn.setBackground(new java.awt.Color(102, 153, 255));
        add_pnlbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_pnlbtn.setForeground(new java.awt.Color(3, 7, 103));
        add_pnlbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_pnlbtn.setPreferredSize(new java.awt.Dimension(360, 130));
        add_pnlbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_pnlbtnMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Swis721 BT", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(3, 7, 103));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DeveloperPage/addeventicon64.png"))); // NOI18N
        jLabel9.setText("ADD");

        javax.swing.GroupLayout add_pnlbtnLayout = new javax.swing.GroupLayout(add_pnlbtn);
        add_pnlbtn.setLayout(add_pnlbtnLayout);
        add_pnlbtnLayout.setHorizontalGroup(
            add_pnlbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_pnlbtnLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel9)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        add_pnlbtnLayout.setVerticalGroup(
            add_pnlbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_pnlbtnLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel3.add(add_pnlbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 130));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 376, -1, -1));

        jPanel6.setBackground(new java.awt.Color(102, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setForeground(new java.awt.Color(3, 7, 103));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.setPreferredSize(new java.awt.Dimension(360, 130));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Swis721 BT", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(3, 7, 103));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DeveloperPage/remove64.png"))); // NOI18N
        jLabel10.setText("REMOVE");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel10)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(30, 30, 30))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 300, 130));

        jPanel7.setBackground(new java.awt.Color(102, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setForeground(new java.awt.Color(3, 7, 103));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.setPreferredSize(new java.awt.Dimension(360, 130));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Swis721 BT", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(3, 7, 103));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DeveloperPage/endedicon64.png"))); // NOI18N
        jLabel11.setText("ENDED");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel11)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, 130));

        MAIN.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 840, 1100, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DeveloperPage/event.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MAIN.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 1050));

        javax.swing.GroupLayout add_desktopLayout = new javax.swing.GroupLayout(add_desktop);
        add_desktop.setLayout(add_desktopLayout);
        add_desktopLayout.setHorizontalGroup(
            add_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        add_desktopLayout.setVerticalGroup(
            add_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );

        MAIN.add(add_desktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 1050));

        getContentPane().add(MAIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 1050));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_pnlbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_pnlbtnMouseClicked
        
    
    clickCount++;

    if (clickCount == 1) {
        ADD_event.setVisible(true);
        MAIN.setVisible(false);
    } else if (clickCount == 2) {
        ADD_event.setVisible(true);
        MAIN.setVisible(false);
    } else if (clickCount == 3) {
        ADD_event.setVisible(true);
        MAIN.setVisible(false);
    } else {
        JOptionPane.showMessageDialog(null, "Maximum of 3 events only.");
        add_pnlbtn.setEnabled(false); // ← this disables the button on 4th click
    }
        
        
        
        

    }//GEN-LAST:event_add_pnlbtnMouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // Confirm before delete
int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this event?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
if (confirm != JOptionPane.YES_OPTION) return;

String captionToDelete = "";
int eventIdIndex = -1; // ← optional if you use eventIds[]

if (selectedIndex == 0) {
    captionToDelete = announce_1.getText();
    eventIdIndex = 0;
} else if (selectedIndex == 1) {
    captionToDelete = announce_2.getText();
    eventIdIndex = 1;
} else if (selectedIndex == 2) {
    captionToDelete = announce_3.getText();
    eventIdIndex = 2;
} else if (selectedIndex == 3) {
    captionToDelete = Past_announce1.getText();
} else if (selectedIndex == 4) {
    captionToDelete = Past_announce2.getText();
} else if (selectedIndex == 5) {
    captionToDelete = Past_announce3.getText();
} else {
    JOptionPane.showMessageDialog(null, "Please select an event to remove.");
    return;
}

// Delete from database
try {
    Connection con = aSQL.getConnection();

    String deleteQuery = "DELETE FROM eventdatabase.event WHERE CAPTION = ?";
    PreparedStatement pst = con.prepareStatement(deleteQuery);
    pst.setString(1, captionToDelete);

    int rows = pst.executeUpdate();
    if (rows > 0) {
        JOptionPane.showMessageDialog(null, "Event deleted successfully.");

        // Hide the panel visually
        if (selectedIndex == 0) {
            Panelremove1.setVisible(false);
            announce_1.setText("");
        } else if (selectedIndex == 1) {
            Panelremove2.setVisible(false);
            announce_2.setText("");
        } else if (selectedIndex == 2) {
            Panelremove3.setVisible(false);
            announce_3.setText("");
        } else if (selectedIndex == 3) {
            Past_event1.setVisible(false);
            Past_announce1.setText("");
        } else if (selectedIndex == 4) {
            Past_event2.setVisible(false);
            Past_announce2.setText("");
        } else if (selectedIndex == 5) {
            Past_event3.setVisible(false);
            Past_announce3.setText("");
        }

        //  Decrease click count if in active announcements
        if (selectedIndex >= 0 && selectedIndex <= 2) {
            if (clickCount > 0) clickCount--;
            add_pnlbtn.setEnabled(true);

            // Optional: Clear event ID if you're tracking it
            if (eventIdIndex != -1) {
                eventIds[eventIdIndex] = -1;
            }
        }

        selectedIndex = -1;
    } else {
        JOptionPane.showMessageDialog(null, "No matching event found.");
    }

    pst.close();
    con.close();
} catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(null, "Error deleting event.");
}

        
    }//GEN-LAST:event_jPanel6MouseClicked

    private void Panelremove1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panelremove1MouseClicked
        // TODO add your handling code here:
        Panel1 = true ;
        Panelremove1.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        selectedIndex = 0;
 
        
    }//GEN-LAST:event_Panelremove1MouseClicked

    private void Panelremove2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panelremove2MouseClicked
        // TODO add your handling code here:
        Panel2 = true ;
        Panelremove2.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        selectedIndex = 1;
               
    }//GEN-LAST:event_Panelremove2MouseClicked

    private void Panelremove3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panelremove3MouseClicked
        // TODO add your handling code here:
        Panel3 = true ;
        Panelremove3.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        selectedIndex = 2;
    
    }//GEN-LAST:event_Panelremove3MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
// Arrays for UI
JPanel[] activePanels = { Panelremove1, Panelremove2, Panelremove3 };
JLabel[] activeCaptions = { announce_1, announce_2, announce_3 };

JPanel[] pastPanels = { Past_event1, Past_event2, Past_event3 };
JLabel[] pastCaptions = { Past_announce1, Past_announce2, Past_announce3 };

if (selectedIndex == -1 || !activePanels[selectedIndex].isVisible()) {
    JOptionPane.showMessageDialog(null, "Please select a valid event panel.");
    return;
}

for (int i = 0; i < pastPanels.length; i++) {
    if (!pastPanels[i].isVisible()) {
        String caption = activeCaptions[selectedIndex].getText();
        int eventId = eventIds[selectedIndex];

        // === DATABASE UPDATE ===
        try {
            Connection con = aSQL.getConnection();

            String updateQuery = "UPDATE eventdatabase.event SET past_event = 'yes', active_announcement = 'no' WHERE id = ?";
            PreparedStatement pst = con.prepareStatement(updateQuery);
            pst.setInt(1, eventId);

            int affected = pst.executeUpdate();

            pst.close();
            con.close();

            if (affected > 0) {
                // UI MOVEMENT ONLY AFTER SUCCESS
                pastCaptions[i].setText(caption);
                pastPanels[i].setVisible(true);
                activePanels[selectedIndex].setVisible(false);

                // Adjust clickCount so user can add new one again
                if (clickCount > 0) {
                    clickCount--;
                    add_pnlbtn.setEnabled(true);
                }

                JOptionPane.showMessageDialog(null, "Event moved to past successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "No matching event found in database.");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error moving event to past.");
        }

        selectedIndex = -1;
        return;
    }
}
                
    }//GEN-LAST:event_jPanel7MouseClicked

    private void Past_event1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Past_event1MouseClicked
        // TODO add your handling code here:
        Panel4 = true ;
        Past_event1.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        selectedIndex = 3;
        
        
    }//GEN-LAST:event_Past_event1MouseClicked

    private void Past_event2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Past_event2MouseClicked
        // TODO add your handling code here:
        Panel5 = true ;
        Past_event2.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        selectedIndex = 4;
        
    }//GEN-LAST:event_Past_event2MouseClicked

    private void Past_event3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Past_event3MouseClicked
        // TODO add your handling code here:
         Panel6 = true ;
        Past_event3.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        selectedIndex = 5;
        
    }//GEN-LAST:event_Past_event3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = aSQL.getConnection();
        String sqlquery = "INSERT INTO eventdatabase.event (IMAGE, CAPTION, active_announcement, past_event) VALUES (?, ?, 'yes', 'no')";
        PreparedStatement pst = con.prepareStatement(sqlquery);
        

        // Create InputStreams from selected file paths
        InputStream is1 = new FileInputStream(new File( pathImageId));
       

        // Set the BLOBs
        pst.setBlob(1, is1);
        pst.setString(2, CaptiontoGet.getText());
       

        pst.execute();

        // Clear image previews (optional    
        event_pnl.setIcon(null);
        CaptiontoGet.setText("");
        
        JOptionPane.showMessageDialog(null, "Data Saved Successfully!");
        ADD_event.setVisible(false);
        MAIN.setVisible(true);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error please fill up the blank", "try again", JOptionPane.ERROR_MESSAGE);
       
    }
        
            // STEP 2: NOW FETCH CAPTIONS FROM DATABASE AFTER INSERT
try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = aSQL.getConnection();

    String query1 = "SELECT id, caption FROM eventdatabase.event WHERE active_announcement = 'yes' AND past_event = 'no' LIMIT 3";
    PreparedStatement pst = con.prepareStatement(query1);
    ResultSet rs = pst.executeQuery();

   int i = 0;
while (rs.next() && i < 3) {
    int id = rs.getInt("id");
    String caption = rs.getString("caption");

    eventIds[i] = id;

    if (i == 0) {
        announce_1.setText(caption);
        Panelremove1.setVisible(true);
    } else if (i == 1) {
        announce_2.setText(caption);
        Panelremove2.setVisible(true);
    } else if (i == 2) {
        announce_3.setText(caption);
        Panelremove3.setVisible(true);
    }

    i++;
}

    rs.close();
    pst.close();
    con.close();

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Failed to load captions from database.");
}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void Add_image_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_image_BTNMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        pathImageId = f.getAbsolutePath();
        try {
            BufferedImage bi = ImageIO.read(new File(pathImageId));
            Image img = bi.getScaledInstance(960, 540, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            event_pnl.setIcon(icon);
  
        } catch (IOException ex) {
            Logger.getLogger(EVENT.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        
    }//GEN-LAST:event_Add_image_BTNMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked
 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ADD_event;
    private javax.swing.JLabel Add_image_BTN;
    private javax.swing.JTextArea CaptiontoGet;
    private javax.swing.JPanel MAIN;
    private javax.swing.JPanel Panelremove1;
    private javax.swing.JPanel Panelremove2;
    private javax.swing.JPanel Panelremove3;
    private javax.swing.JLabel Past_announce1;
    private javax.swing.JLabel Past_announce2;
    private javax.swing.JLabel Past_announce3;
    private javax.swing.JPanel Past_event1;
    private javax.swing.JPanel Past_event2;
    private javax.swing.JPanel Past_event3;
    private javax.swing.JDesktopPane add_desktop;
    private javax.swing.JPanel add_pnlbtn;
    private javax.swing.JLabel announce_1;
    private javax.swing.JLabel announce_2;
    private javax.swing.JLabel announce_3;
    private javax.swing.JLabel event_pnl;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
