/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;

/**
 *
 * @author Matt
 */
public class Citizen extends javax.swing.JFrame {

    static void DISPOSE_ON_CLOSE() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form Citizen
     */
    Color DefaultColor, ClickedColor;
    public Citizen() {
        initComponents();
       
        DefaultColor = new Color(0,51,153);
        ClickedColor = new Color(0,0,102);
        
        PD.setBackground(DefaultColor);
        DD.setBackground(DefaultColor);
        INFO.setBackground(DefaultColor);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        signpnl = new javax.swing.JPanel();
        signlbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        PDPanel = new javax.swing.JPanel();
        PD = new javax.swing.JLabel();
        DPPanel = new javax.swing.JPanel();
        DD = new javax.swing.JLabel();
        INFOPanel = new javax.swing.JPanel();
        INFO = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/no.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Barangay Information System ");

        signpnl.setBackground(new java.awt.Color(0, 0, 102));
        signpnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signpnlMouseClicked(evt);
            }
        });

        signlbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        signlbl.setForeground(new java.awt.Color(51, 204, 255));
        signlbl.setText("- Sign Up Application Form ");
        signlbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signlblMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("- Citizen");

        javax.swing.GroupLayout signpnlLayout = new javax.swing.GroupLayout(signpnl);
        signpnl.setLayout(signpnlLayout);
        signpnlLayout.setHorizontalGroup(
            signpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signpnlLayout.createSequentialGroup()
                .addComponent(signlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        signpnlLayout.setVerticalGroup(
            signpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signpnlLayout.createSequentialGroup()
                .addGroup(signpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(signpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(769, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(signpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));

        PDPanel.setBackground(new java.awt.Color(0, 51, 153));
        PDPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PDPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PDPanelMousePressed(evt);
            }
        });

        PD.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        PD.setForeground(new java.awt.Color(255, 255, 255));
        PD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N
        PD.setText("Personal Details");
        PD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PDMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PDMousePressed(evt);
            }
        });

        javax.swing.GroupLayout PDPanelLayout = new javax.swing.GroupLayout(PDPanel);
        PDPanel.setLayout(PDPanelLayout);
        PDPanelLayout.setHorizontalGroup(
            PDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PDPanelLayout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addComponent(PD, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        PDPanelLayout.setVerticalGroup(
            PDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        DPPanel.setBackground(new java.awt.Color(0, 51, 153));
        DPPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DPPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DPPanelMousePressed(evt);
            }
        });

        DD.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        DD.setForeground(new java.awt.Color(255, 255, 255));
        DD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/document.png"))); // NOI18N
        DD.setText("Document Details");
        DD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DDMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DDMousePressed(evt);
            }
        });

        javax.swing.GroupLayout DPPanelLayout = new javax.swing.GroupLayout(DPPanel);
        DPPanel.setLayout(DPPanelLayout);
        DPPanelLayout.setHorizontalGroup(
            DPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DPPanelLayout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(DD, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        DPPanelLayout.setVerticalGroup(
            DPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DPPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        INFOPanel.setBackground(new java.awt.Color(0, 51, 153));
        INFOPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INFOPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                INFOPanelMousePressed(evt);
            }
        });

        INFO.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        INFO.setForeground(new java.awt.Color(255, 255, 255));
        INFO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/information.png"))); // NOI18N
        INFO.setText("Information");
        INFO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                INFOMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                INFOMousePressed(evt);
            }
        });

        javax.swing.GroupLayout INFOPanelLayout = new javax.swing.GroupLayout(INFOPanel);
        INFOPanel.setLayout(INFOPanelLayout);
        INFOPanelLayout.setHorizontalGroup(
            INFOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, INFOPanelLayout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(INFO, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        INFOPanelLayout.setVerticalGroup(
            INFOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, INFOPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(INFO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PDPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DPPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(INFOPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PDPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DPPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(INFOPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1090));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void PDPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PDPanelMousePressed
     
        PDPanel.setBackground(ClickedColor);
        DPPanel.setBackground(DefaultColor);
        INFOPanel.setBackground(DefaultColor);
        
    }//GEN-LAST:event_PDPanelMousePressed

    private void PDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PDMousePressed
        PDPanel.setBackground(ClickedColor);
        DPPanel.setBackground(DefaultColor);
        INFOPanel.setBackground(DefaultColor);
        
    }//GEN-LAST:event_PDMousePressed

    private void DDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DDMousePressed
        PDPanel.setBackground(DefaultColor);
        DPPanel.setBackground(ClickedColor);
        INFOPanel.setBackground(DefaultColor);
        
    }//GEN-LAST:event_DDMousePressed

    private void INFOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INFOMousePressed
        PDPanel.setBackground(DefaultColor);
        DPPanel.setBackground(DefaultColor);
        INFOPanel.setBackground(ClickedColor);
        
    }//GEN-LAST:event_INFOMousePressed

    private void DPPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DPPanelMousePressed
        PDPanel.setBackground(DefaultColor);
        DPPanel.setBackground(ClickedColor);
        INFOPanel.setBackground(DefaultColor);
        
    }//GEN-LAST:event_DPPanelMousePressed

    private void INFOPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INFOPanelMousePressed
        PDPanel.setBackground(DefaultColor);
        DPPanel.setBackground(DefaultColor);
        INFOPanel.setBackground(ClickedColor);
        
    }//GEN-LAST:event_INFOPanelMousePressed

    private void PDPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PDPanelMouseClicked
        PersonalDetail personal = new PersonalDetail();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(personal).setVisible(true);
    }//GEN-LAST:event_PDPanelMouseClicked

    private void PDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PDMouseClicked
        PersonalDetail personal = new PersonalDetail();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(personal).setVisible(true);
    }//GEN-LAST:event_PDMouseClicked

    private void DPPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DPPanelMouseClicked
        DocumentDetail document = new DocumentDetail();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(document).setVisible(true);
    }//GEN-LAST:event_DPPanelMouseClicked

    private void INFOPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INFOPanelMouseClicked
        Informations combine = new Informations();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(combine).setVisible(true);
    }//GEN-LAST:event_INFOPanelMouseClicked

    private void DDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DDMouseClicked
        DocumentDetail document = new DocumentDetail();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(document).setVisible(true);
    }//GEN-LAST:event_DDMouseClicked

    private void INFOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_INFOMouseClicked
        Informations combine = new Informations();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(combine).setVisible(true);
        
        
    }//GEN-LAST:event_INFOMouseClicked

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseReleased

    private void signlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signlblMouseClicked
        new Sign_Up().setVisible(true);
        signlbl.setBackground(DefaultColor);
        this.dispose();
    }//GEN-LAST:event_signlblMouseClicked

    private void signpnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signpnlMouseClicked
        new Sign_Up().setVisible(true);
        signpnl.setBackground(DefaultColor);
        this.dispose();
    }//GEN-LAST:event_signpnlMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Citizen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Citizen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Citizen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Citizen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Citizen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DD;
    private javax.swing.JPanel DPPanel;
    private javax.swing.JLabel INFO;
    private javax.swing.JPanel INFOPanel;
    private javax.swing.JLabel PD;
    private javax.swing.JPanel PDPanel;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel signlbl;
    private javax.swing.JPanel signpnl;
    // End of variables declaration//GEN-END:variables
}
