/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Paul Daniel Reyes
 */
public class DonationMenu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public DonationMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lblPCA = new javax.swing.JLabel();
        lblPM = new javax.swing.JLabel();
        btnNO = new javax.swing.JRadioButton();
        btnYES = new javax.swing.JRadioButton();
        lblquestion = new javax.swing.JLabel();
        txtMONEY = new javax.swing.JTextField();
        txtREASON = new javax.swing.JTextField();
        lblREASON = new javax.swing.JLabel();
        lblmoney = new javax.swing.JLabel();
        lblDONATION = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DONATION");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.setOpaque(false);
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 930, 120, 110));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/previous (1).png"))); // NOI18N
        jLabel12.setText("Go back");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lblPCA.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lblPCA.setForeground(new java.awt.Color(255, 255, 255));
        lblPCA.setText("PLEASE CHOOSE A ");
        jPanel1.add(lblPCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 830, 250, 20));

        lblPM.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lblPM.setForeground(new java.awt.Color(255, 255, 255));
        lblPM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPM.setText("PAYMENT METHODS:");
        jPanel1.add(lblPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 860, -1, -1));

        buttonGroup1.add(btnNO);
        btnNO.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        btnNO.setForeground(new java.awt.Color(255, 255, 255));
        btnNO.setText("NO");
        btnNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNOActionPerformed(evt);
            }
        });
        jPanel1.add(btnNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 670, 110, 50));

        buttonGroup1.add(btnYES);
        btnYES.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        btnYES.setForeground(new java.awt.Color(255, 255, 255));
        btnYES.setText("YES");
        btnYES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYESActionPerformed(evt);
            }
        });
        jPanel1.add(btnYES, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 670, 100, 50));

        lblquestion.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        lblquestion.setForeground(new java.awt.Color(255, 255, 255));
        lblquestion.setText("Do you want your name to be hidden or anounymous?");
        jPanel1.add(lblquestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 1310, 70));

        txtMONEY.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtMONEY.setForeground(new java.awt.Color(0, 0, 0));
        txtMONEY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMONEYActionPerformed(evt);
            }
        });
        jPanel1.add(txtMONEY, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 480, 60));

        txtREASON.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtREASON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtREASONActionPerformed(evt);
            }
        });
        jPanel1.add(txtREASON, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 1550, 150));

        lblREASON.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        lblREASON.setForeground(new java.awt.Color(255, 255, 255));
        lblREASON.setText("What is your reason? ");
        jPanel1.add(lblREASON, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        lblmoney.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        lblmoney.setForeground(new java.awt.Color(255, 255, 255));
        lblmoney.setText("Amount of Money: ");
        jPanel1.add(lblmoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        lblDONATION.setFont(new java.awt.Font("Georgia", 1, 80)); // NOI18N
        lblDONATION.setForeground(new java.awt.Color(255, 255, 255));
        lblDONATION.setText("DONATION");
        jPanel1.add(lblDONATION, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Georgia", 1, 80)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("DONATION");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 500, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Paul Daniel Reyes\\Documents\\BSU - School Docu\\2nd Year\\donation.png")); // NOI18N
        jLabel1.setText(".");
        jLabel1.setPreferredSize(new java.awt.Dimension(1920, 1240));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1085));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMONEYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMONEYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMONEYActionPerformed

    private void txtREASONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtREASONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtREASONActionPerformed

    private void btnNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNOActionPerformed

    private void btnYESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYESActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        new DonationGCash1().setVisible(true);
        
        String money = txtMONEY.getText();
        
        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = aSQL.getConnection();

                                                                                 
            String sql = "INSERT INTO donation (amount_money)" + "VALUES (?)";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, money);
            
            int rows = stmt.executeUpdate();
               if (rows > 0) {
                   JOptionPane.showMessageDialog(this, "Data saved successfully!");
                   clearFormFields(); // Optional: Implement this to clear all input fields
               }
            
            
            con.close();
            stmt.close();
        } catch (SQLException e) {
               JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
               e.printStackTrace();
           } catch (ClassNotFoundException ex) {
               JOptionPane.showMessageDialog(this, "Driver Error: " + ex.getMessage());
               ex.printStackTrace();
           }
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked

        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonationMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonationMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonationMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonationMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonationMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnNO;
    private javax.swing.JRadioButton btnYES;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDONATION;
    private javax.swing.JLabel lblPCA;
    private javax.swing.JLabel lblPM;
    private javax.swing.JLabel lblREASON;
    private javax.swing.JLabel lblmoney;
    private javax.swing.JLabel lblquestion;
    private javax.swing.JTextField txtMONEY;
    private javax.swing.JTextField txtREASON;
    // End of variables declaration//GEN-END:variables

    private void clearFormFields() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
