/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
/**
 *
 * @author santo
 */
public class Home extends javax.swing.JInternalFrame {

    /**
     * Creates new form bagonghome
     */
    
    int currentIndex = 0;
    JLabel[] images;
    JScrollPane[] captionScrolls;
      
    List<ImageIcon> imageList = new ArrayList<>();
    List<String> captionList = new ArrayList<>();
      
    public void loadDataFromDatabase() {
        try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = aSQL.getConnection();

    // Tamang SQL query
    String query = "SELECT IMAGE, CAPTION FROM eventdatabase.event WHERE active_announcement = 'yes' ORDER BY id ASC LIMIT 3";
    PreparedStatement pst = con.prepareStatement(query);
    ResultSet rs = pst.executeQuery();

    while (rs.next()) {
        // Add caption
        captionList.add(rs.getString("CAPTION"));

        // Convert image
        Blob blob = rs.getBlob("IMAGE");
        InputStream is = blob.getBinaryStream();
        BufferedImage bufferedImage = ImageIO.read(is);
        Image scaledImage = bufferedImage.getScaledInstance(1070, 710, Image.SCALE_SMOOTH);
        imageList.add(new ImageIcon(scaledImage));
    }

    rs.close();
    pst.close();
    con.close();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to load announcements.");
        }
    }

    public void showAnnouncement(int index) {
    if (index >= 0 && index < imageList.size()) {
        Announcement_1.setIcon(imageList.get(index));
        TXT_1.setText(captionList.get(index));
    }
}

public void loadpastevent() {
    try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = aSQL.getConnection();

    // Query only past events that are not active
    String query = "SELECT CAPTION FROM eventdatabase.event WHERE past_event = 'yes' AND active_announcement = 'no' ORDER BY id ASC LIMIT 3";
    PreparedStatement pst = con.prepareStatement(query);
    ResultSet rs = pst.executeQuery();

    int index = 0;
    while (rs.next()) {
        String caption = rs.getString("CAPTION");

        if (index == 0) {
            Past_event1.setText(caption);
            panelannounce1.setVisible(true);
        } else if (index == 1) {
            Past_event2.setText(caption);
            panelannounce2.setVisible(true);
        } else if (index == 2) {
            Past_event3.setText(caption);
            panelannounce3.setVisible(true);
        }
        index++;
    }

    // Hide remaining panels kung wala nang data
    if (index < 3) {
        if (index <= 0) panelannounce1.setVisible(false);
        if (index <= 1) panelannounce2.setVisible(false);
        if (index <= 2) panelannounce3.setVisible(false);
    }

    rs.close();
    pst.close();
    con.close();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Failed to load past events.");
    }
}

    
    

    public Home() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        loadDataFromDatabase();
        showAnnouncement(currentIndex);
        loadpastevent();
         
        }
     

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Announcement_1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        back_BTN = new javax.swing.JLabel();
        next_BTN = new javax.swing.JLabel();
        TXT_Announcement1 = new javax.swing.JScrollPane();
        TXT_1 = new javax.swing.JTextArea();
        TXT_Announcement2 = new javax.swing.JScrollPane();
        TXT_2 = new javax.swing.JTextArea();
        panelannounce1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Past_event1 = new javax.swing.JTextArea();
        panelannounce2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Past_event2 = new javax.swing.JTextArea();
        panelannounce3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Past_event3 = new javax.swing.JTextArea();
        TXT_Announcement3 = new javax.swing.JScrollPane();
        TXT_3 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(3, 7, 103));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(Announcement_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1070, 710));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 165, 1070, 710));

        jLabel2.setBackground(new java.awt.Color(3, 7, 103));
        jLabel2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(3, 7, 103));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/announcementicon64.png"))); // NOI18N
        jLabel2.setText("ANNOUNCEMENT");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pastevent64.png"))); // NOI18N
        jLabel3.setText("PAST EVENTS");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 20, 470, 120));

        back_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage/back button.png"))); // NOI18N
        back_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_BTNMouseClicked(evt);
            }
        });
        jPanel2.add(back_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        next_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage/next button.png"))); // NOI18N
        next_BTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                next_BTNMouseClicked(evt);
            }
        });
        jPanel2.add(next_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 480, 64, 64));

        TXT_Announcement1.setBackground(new java.awt.Color(3, 7, 103));
        TXT_Announcement1.setForeground(new java.awt.Color(3, 7, 103));
        TXT_Announcement1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        TXT_Announcement1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        TXT_Announcement1.setOpaque(false);

        TXT_1.setEditable(false);
        TXT_1.setBackground(new java.awt.Color(3, 7, 103));
        TXT_1.setColumns(20);
        TXT_1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        TXT_1.setForeground(new java.awt.Color(255, 255, 255));
        TXT_1.setLineWrap(true);
        TXT_1.setRows(5);
        TXT_1.setWrapStyleWord(true);
        TXT_1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TXT_Announcement1.setViewportView(TXT_1);

        jPanel2.add(TXT_Announcement1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 920, 1070, 220));

        TXT_Announcement2.setBackground(new java.awt.Color(3, 7, 103));
        TXT_Announcement2.setForeground(new java.awt.Color(3, 7, 103));
        TXT_Announcement2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        TXT_Announcement2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        TXT_Announcement2.setOpaque(false);

        TXT_2.setEditable(false);
        TXT_2.setBackground(new java.awt.Color(3, 7, 103));
        TXT_2.setColumns(20);
        TXT_2.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        TXT_2.setForeground(new java.awt.Color(255, 255, 255));
        TXT_2.setLineWrap(true);
        TXT_2.setRows(5);
        TXT_2.setWrapStyleWord(true);
        TXT_2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TXT_2.setEnabled(false);
        TXT_Announcement2.setViewportView(TXT_2);

        jPanel2.add(TXT_Announcement2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 920, 1070, 220));

        panelannounce1.setBackground(new java.awt.Color(3, 7, 103));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Past_event1.setEditable(false);
        Past_event1.setBackground(new java.awt.Color(3, 7, 103));
        Past_event1.setColumns(20);
        Past_event1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Past_event1.setForeground(new java.awt.Color(255, 255, 255));
        Past_event1.setLineWrap(true);
        Past_event1.setRows(5);
        Past_event1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(Past_event1);

        javax.swing.GroupLayout panelannounce1Layout = new javax.swing.GroupLayout(panelannounce1);
        panelannounce1.setLayout(panelannounce1Layout);
        panelannounce1Layout.setHorizontalGroup(
            panelannounce1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );
        panelannounce1Layout.setVerticalGroup(
            panelannounce1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        jPanel2.add(panelannounce1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 130, 470, 330));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Past_event2.setEditable(false);
        Past_event2.setBackground(new java.awt.Color(3, 7, 103));
        Past_event2.setColumns(20);
        Past_event2.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Past_event2.setForeground(new java.awt.Color(255, 255, 255));
        Past_event2.setRows(5);
        jScrollPane2.setViewportView(Past_event2);

        javax.swing.GroupLayout panelannounce2Layout = new javax.swing.GroupLayout(panelannounce2);
        panelannounce2.setLayout(panelannounce2Layout);
        panelannounce2Layout.setHorizontalGroup(
            panelannounce2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelannounce2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelannounce2Layout.setVerticalGroup(
            panelannounce2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );

        jPanel2.add(panelannounce2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 480, 470, 370));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Past_event3.setEditable(false);
        Past_event3.setBackground(new java.awt.Color(3, 7, 103));
        Past_event3.setColumns(20);
        Past_event3.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Past_event3.setForeground(new java.awt.Color(255, 255, 255));
        Past_event3.setRows(5);
        jScrollPane3.setViewportView(Past_event3);

        javax.swing.GroupLayout panelannounce3Layout = new javax.swing.GroupLayout(panelannounce3);
        panelannounce3.setLayout(panelannounce3Layout);
        panelannounce3Layout.setHorizontalGroup(
            panelannounce3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelannounce3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelannounce3Layout.setVerticalGroup(
            panelannounce3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        jPanel2.add(panelannounce3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 870, -1, 300));

        TXT_Announcement3.setBackground(new java.awt.Color(3, 7, 103));
        TXT_Announcement3.setForeground(new java.awt.Color(3, 7, 103));
        TXT_Announcement3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        TXT_Announcement3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        TXT_Announcement3.setOpaque(false);

        TXT_3.setEditable(false);
        TXT_3.setBackground(new java.awt.Color(3, 7, 103));
        TXT_3.setColumns(20);
        TXT_3.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        TXT_3.setForeground(new java.awt.Color(255, 255, 255));
        TXT_3.setLineWrap(true);
        TXT_3.setRows(5);
        TXT_3.setWrapStyleWord(true);
        TXT_3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TXT_Announcement3.setViewportView(TXT_3);

        jPanel2.add(TXT_Announcement3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 920, 1070, 220));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1240));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Homepage/newsss ui.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1240));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void next_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_next_BTNMouseClicked
        // TODO add your handling code here:
        if (currentIndex < imageList.size() - 1) {
        currentIndex++;
        showAnnouncement(currentIndex);
    }
        

    }//GEN-LAST:event_next_BTNMouseClicked

    private void back_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_BTNMouseClicked
        // TODO add your handling code here:
    if (currentIndex > 0) {
        currentIndex--;
        showAnnouncement(currentIndex);
    }
    }//GEN-LAST:event_back_BTNMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Announcement_1;
    private javax.swing.JTextArea Past_event1;
    private javax.swing.JTextArea Past_event2;
    private javax.swing.JTextArea Past_event3;
    private javax.swing.JTextArea TXT_1;
    private javax.swing.JTextArea TXT_2;
    private javax.swing.JTextArea TXT_3;
    private javax.swing.JScrollPane TXT_Announcement1;
    private javax.swing.JScrollPane TXT_Announcement2;
    private javax.swing.JScrollPane TXT_Announcement3;
    private javax.swing.JLabel back_BTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel next_BTN;
    private javax.swing.JPanel panelannounce1;
    private javax.swing.JPanel panelannounce2;
    private javax.swing.JPanel panelannounce3;
    // End of variables declaration//GEN-END:variables

    void setTextFromFrameA(String myText) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    void setTextFromEVENT(String myText) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
