/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;


/**
 *
 * @author Matt
 */
public class Informations extends javax.swing.JInternalFrame {

    /**
     * Creates new form PersonalDetail
     */
    
    
    public Informations() {
        initComponents();
        
        btnCONFIRM.setEnabled(false);
       
        
        
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtEMERGENCY = new javax.swing.JTextField();
        txtRELATIONSHIP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLAST = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtFIRST = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        cmbSUFFIX = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txtPERADD = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        txtGENDER = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        cmbCIVIL_STATUS = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        txtOCCUPATION = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        txtAGE = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txtFATHER_NAME = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        txtFATHER_AGE = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        txtFATHER_ADDRESS = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        txtFATHER_PHONE = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        txtFATHER_DOB = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        txtFATHER_OCCUPATION = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txtMOTHER_NAME = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        txtMOTHER_AGE = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        txtMOTHER_ADDRESS = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtMOTHER_PHONE = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        txtMOTHER_DOB = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        txtMOTHER_OCCUPATION = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txtEMERADD = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        txtEMERPHONE = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtALTERNATE = new javax.swing.JTextField();
        txtALTPHONE = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        btnCONFIRM = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        txtUSERNAME = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        txtPASSWORD = new javax.swing.JPasswordField();
        txtMIDDLE = new javax.swing.JTextField();
        txtCURADD = new javax.swing.JTextField();
        txtPHONE = new javax.swing.JTextField();
        txtRELIGION = new javax.swing.JTextField();
        cmbNATIONALITY = new javax.swing.JTextField();
        btnREFRESH = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        jLabel7.setText("Phone Number:");

        setTitle("Personal Detail");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N
        jLabel2.setText("I. Personal Information");

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N
        jLabel19.setText("II. Family Background");

        jLabel39.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N
        jLabel39.setText("I. Personal Details");

        jLabel43.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N
        jLabel43.setText("II. Family Background");

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N
        jLabel4.setText("I. Personal Information");

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N
        jLabel20.setText("II. Family Background");

        jLabel41.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N
        jLabel41.setText("I. Personal Details");

        jLabel74.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N
        jLabel74.setText("II. Family Background");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 406, Short.MAX_VALUE)
                .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(416, 416, 416))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(921, 921, 921)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1234, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(416, 416, 416))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(921, 921, 921)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel19))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1990, 50));

        jPanel5.setBackground(new java.awt.Color(246, 238, 227));
        jPanel5.setPreferredSize(new java.awt.Dimension(1920, 965));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pin.png"))); // NOI18N
        jLabel17.setText("Emergency Contact Person:");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 751, -1, -1));

        jLabel40.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pin.png"))); // NOI18N
        jLabel40.setText("Relationship to you:");
        jPanel5.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 796, -1, -1));

        txtEMERGENCY.setEnabled(false);
        jPanel5.add(txtEMERGENCY, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 755, 404, 27));

        txtRELATIONSHIP.setEnabled(false);
        jPanel5.add(txtRELATIONSHIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 794, 401, 30));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Gender:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 469, 91, -1));

        txtLAST.setEnabled(false);
        txtLAST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLASTActionPerformed(evt);
            }
        });
        jPanel5.add(txtLAST, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 71, 340, 30));

        jLabel42.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Last Name:");
        jPanel5.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 74, 188, -1));

        txtFIRST.setEnabled(false);
        jPanel5.add(txtFIRST, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 113, 340, 30));

        jLabel47.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("First Name:");
        jPanel5.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 116, 188, -1));

        jLabel48.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Middle Name:");
        jPanel5.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 155, 188, -1));

        cmbSUFFIX.setEnabled(false);
        jPanel5.add(cmbSUFFIX, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 340, 30));

        jLabel49.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Permanent Address:");
        jPanel5.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 379, 187, -1));

        txtPERADD.setEnabled(false);
        jPanel5.add(txtPERADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 370, 340, 30));

        jLabel32.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("House Number/ Blk Number/ Street/ Barangay");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 403, 340, -1));

        jLabel50.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("Current Address:");
        jPanel5.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 284, 188, -1));

        txtDOB.setEnabled(false);
        jPanel5.add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 340, -1));

        jLabel51.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 0));
        jLabel51.setText("House Number/ Blk Number/ Street/ Barangay");
        jPanel5.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 317, 340, -1));

        jLabel52.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 0, 0));
        jLabel52.setText("Phone Number:");
        jPanel5.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 435, 173, -1));

        txtGENDER.setEnabled(false);
        jPanel5.add(txtGENDER, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 340, 30));

        jLabel14.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Civil Status:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 507, 120, 25));

        jLabel15.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Nationality:");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 555, 120, 25));

        jLabel53.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 0, 0));
        jLabel53.setText("Religion:");
        jPanel5.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 602, 120, -1));

        cmbCIVIL_STATUS.setEnabled(false);
        jPanel5.add(cmbCIVIL_STATUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 340, 30));

        jLabel54.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(0, 0, 0));
        jLabel54.setText("Occupation:");
        jPanel5.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 644, 120, -1));

        txtOCCUPATION.setEnabled(false);
        txtOCCUPATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOCCUPATIONActionPerformed(evt);
            }
        });
        jPanel5.add(txtOCCUPATION, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 641, 340, 30));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details.png"))); // NOI18N
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 751, -1, 70));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        jLabel38.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alarm.png"))); // NOI18N
        jLabel38.setText("IV. Emergency Information");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1393, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 683, -1, -1));

        jLabel55.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 0, 0));
        jLabel55.setText("Age:");
        jPanel5.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 242, 188, -1));

        txtAGE.setEnabled(false);
        jPanel5.add(txtAGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 239, 340, 30));

        jLabel44.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Full Name:");
        jPanel5.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 149, 181, -1));

        txtFATHER_NAME.setEnabled(false);
        jPanel5.add(txtFATHER_NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 146, 340, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/man (1).png"))); // NOI18N
        jLabel1.setText("Father's Background");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 57, -1, 77));

        jLabel56.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 0, 0));
        jLabel56.setText("Surname, First Name, Middle Name");
        jPanel5.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 182, 340, -1));

        jLabel57.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 0, 0));
        jLabel57.setText("Age:");
        jPanel5.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 181, -1));

        txtFATHER_AGE.setEnabled(false);
        jPanel5.add(txtFATHER_AGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, 340, 30));

        jLabel58.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 0, 0));
        jLabel58.setText("Permanent Address:");
        jPanel5.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 192, -1));

        txtFATHER_ADDRESS.setEnabled(false);
        jPanel5.add(txtFATHER_ADDRESS, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 250, 340, 30));

        jLabel33.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("House Number/ Blk Number/ Street/ Barangay");
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 290, 340, 20));

        jLabel59.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 0, 0));
        jLabel59.setText("Phone Number:");
        jPanel5.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 192, -1));

        txtFATHER_PHONE.setEnabled(false);
        jPanel5.add(txtFATHER_PHONE, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 330, 340, 30));

        jLabel60.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 0, 0));
        jLabel60.setText("Suffix:");
        jPanel5.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 197, 188, -1));

        jLabel61.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(0, 0, 0));
        jLabel61.setText("Date of Birth:");
        jPanel5.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 343, 164, -1));

        jLabel62.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(0, 0, 0));
        jLabel62.setText("Date of Birth:");
        jPanel5.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 192, -1));

        txtFATHER_DOB.setEnabled(false);
        txtFATHER_DOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFATHER_DOBActionPerformed(evt);
            }
        });
        jPanel5.add(txtFATHER_DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 380, 340, 30));

        jLabel64.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(0, 0, 0));
        jLabel64.setText("Occupation:");
        jPanel5.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, 182, -1));

        txtFATHER_OCCUPATION.setEnabled(false);
        txtFATHER_OCCUPATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFATHER_OCCUPATIONActionPerformed(evt);
            }
        });
        jPanel5.add(txtFATHER_OCCUPATION, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 480, 340, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/woman (2).png"))); // NOI18N
        jLabel3.setText("Mother's Background");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1259, 57, -1, 77));

        jLabel45.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Full Name:");
        jPanel5.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 149, 181, -1));

        txtMOTHER_NAME.setEnabled(false);
        jPanel5.add(txtMOTHER_NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(1539, 146, 340, 30));

        jLabel65.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(0, 0, 0));
        jLabel65.setText("Surname, First Name, Middle Name");
        jPanel5.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(1539, 182, 340, -1));

        txtMOTHER_AGE.setEnabled(false);
        jPanel5.add(txtMOTHER_AGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 210, 340, 30));

        jLabel66.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(0, 0, 0));
        jLabel66.setText("Age:");
        jPanel5.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 210, 181, -1));

        jLabel67.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(0, 0, 0));
        jLabel67.setText("Permanent Address:");
        jPanel5.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 250, 192, -1));

        txtMOTHER_ADDRESS.setEnabled(false);
        jPanel5.add(txtMOTHER_ADDRESS, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 250, 340, 30));

        jLabel34.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("House Number/ Blk Number/ Street/ Barangay");
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 290, 340, 20));

        txtMOTHER_PHONE.setEnabled(false);
        jPanel5.add(txtMOTHER_PHONE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 330, 340, 30));

        jLabel68.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(0, 0, 0));
        jLabel68.setText("Phone Number:");
        jPanel5.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 330, 192, -1));

        jLabel69.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(0, 0, 0));
        jLabel69.setText("Date of Birth:");
        jPanel5.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 380, 192, -1));

        txtMOTHER_DOB.setEnabled(false);
        txtMOTHER_DOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMOTHER_DOBActionPerformed(evt);
            }
        });
        jPanel5.add(txtMOTHER_DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 380, 340, 30));

        jLabel71.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(0, 0, 0));
        jLabel71.setText("Occupation:");
        jPanel5.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 490, 182, -1));

        txtMOTHER_OCCUPATION.setEnabled(false);
        txtMOTHER_OCCUPATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMOTHER_OCCUPATIONActionPerformed(evt);
            }
        });
        jPanel5.add(txtMOTHER_OCCUPATION, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 480, 340, 30));

        jLabel46.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pin.png"))); // NOI18N
        jLabel46.setText("Emergency Contact Address:");
        jPanel5.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 860, -1, -1));

        txtEMERADD.setEnabled(false);
        jPanel5.add(txtEMERADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 862, 388, 30));

        jLabel36.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel36.setText("e.g., Father, Mother, Spouse, Friend, Sibling");
        jPanel5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 834, 340, 20));

        jLabel72.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(0, 0, 0));
        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pin.png"))); // NOI18N
        jLabel72.setText("Phone Number:");
        jPanel5.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 904, -1, -1));

        txtEMERPHONE.setEnabled(false);
        txtEMERPHONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEMERPHONEActionPerformed(evt);
            }
        });
        jPanel5.add(txtEMERPHONE, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 906, 402, 30));

        jLabel18.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pin.png"))); // NOI18N
        jLabel18.setText("Alternate Contact Person:");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1082, 773, -1, -1));

        txtALTERNATE.setEnabled(false);
        jPanel5.add(txtALTERNATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1408, 777, 404, 27));

        txtALTPHONE.setEnabled(false);
        txtALTPHONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtALTPHONEActionPerformed(evt);
            }
        });
        jPanel5.add(txtALTPHONE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1408, 824, 402, 30));

        jLabel73.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(0, 0, 0));
        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pin.png"))); // NOI18N
        jLabel73.setText("Phone Number:");
        jPanel5.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(1082, 822, -1, -1));

        btnCONFIRM.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnCONFIRM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/next.png"))); // NOI18N
        btnCONFIRM.setText("Show/Confirm Informations");
        btnCONFIRM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), null, null));
        btnCONFIRM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCONFIRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCONFIRMActionPerformed(evt);
            }
        });
        jPanel5.add(btnCONFIRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1573, 882, 315, 40));

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));

        jLabel75.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N
        jLabel75.setText("III. Create Account");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(767, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel75, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 1300, 40));

        jLabel76.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(0, 0, 0));
        jLabel76.setText("Username:");
        jPanel5.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 590, 181, -1));

        txtUSERNAME.setEnabled(false);
        jPanel5.add(txtUSERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 580, 340, 30));

        jLabel77.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(0, 0, 0));
        jLabel77.setText("Password:");
        jPanel5.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 640, 181, -1));

        txtPASSWORD.setEnabled(false);
        txtPASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPASSWORDActionPerformed(evt);
            }
        });
        jPanel5.add(txtPASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 630, 340, 30));

        txtMIDDLE.setEnabled(false);
        jPanel5.add(txtMIDDLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 155, 340, 30));

        txtCURADD.setEnabled(false);
        jPanel5.add(txtCURADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 281, 340, 30));

        txtPHONE.setEnabled(false);
        jPanel5.add(txtPHONE, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 432, 340, 30));

        txtRELIGION.setEnabled(false);
        jPanel5.add(txtRELIGION, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 599, 340, 30));

        cmbNATIONALITY.setEnabled(false);
        jPanel5.add(cmbNATIONALITY, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 340, 30));

        btnREFRESH.setText("REFRESH");
        btnREFRESH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREFRESHActionPerformed(evt);
            }
        });
        jPanel5.add(btnREFRESH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 880, 110, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled design (16).png"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1970, 930));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1980, 990));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing

    }//GEN-LAST:event_formInternalFrameClosing

    private void txtOCCUPATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOCCUPATIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOCCUPATIONActionPerformed

    private void txtFATHER_DOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFATHER_DOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFATHER_DOBActionPerformed

    private void txtFATHER_OCCUPATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFATHER_OCCUPATIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFATHER_OCCUPATIONActionPerformed

    private void txtMOTHER_DOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMOTHER_DOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMOTHER_DOBActionPerformed

    private void txtMOTHER_OCCUPATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMOTHER_OCCUPATIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMOTHER_OCCUPATIONActionPerformed

    private void txtEMERPHONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEMERPHONEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEMERPHONEActionPerformed

    private void txtALTPHONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtALTPHONEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtALTPHONEActionPerformed

    private void txtPASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPASSWORDActionPerformed

    private void btnREFRESHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREFRESHActionPerformed
        btnCONFIRM.setEnabled(true);
        
            try {
        
        //...
        
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = aSQL.getConnection();

                String sql = "SELECT * FROM barangay_finals.information ORDER BY citizen_id DESC LIMIT 1";
                PreparedStatement pst = con.prepareStatement(sql);

                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    txtUSERNAME.setText(rs.getString("username"));
                    txtPASSWORD.setText(rs.getString("password"));
                    txtFIRST.setText(rs.getString("first_name"));
                    txtMIDDLE.setText(rs.getString("middle_name"));
                    txtLAST.setText(rs.getString("last_name"));
                    cmbSUFFIX.setText(rs.getString("suffix"));
                    txtAGE.setText(rs.getString("age"));
                    txtCURADD.setText(rs.getString("current_address"));
                    txtPERADD.setText(rs.getString("permanent_address"));
                    txtGENDER.setText(rs.getString("gender"));
                    txtPHONE.setText(rs.getString("phone_number"));
                    txtDOB.setText(rs.getString("date_of_birth"));
                    cmbCIVIL_STATUS.setText(rs.getString("civil_status"));
                    cmbNATIONALITY.setText(rs.getString("nationality"));
                    txtOCCUPATION.setText(rs.getString("occupation"));
                    txtRELIGION.setText(rs.getString("religion"));
                    txtFATHER_NAME.setText(rs.getString("father_name"));
                    txtFATHER_AGE.setText(rs.getString("father_age"));
                    txtFATHER_ADDRESS.setText(rs.getString("father_address"));
                    txtFATHER_PHONE.setText(rs.getString("father_phone_number"));
                    txtFATHER_DOB.setText(rs.getString("father_date_of_birth"));
                    txtFATHER_OCCUPATION.setText(rs.getString("father_occupation"));
                    txtMOTHER_NAME.setText(rs.getString("mother_name"));
                    txtMOTHER_AGE.setText(rs.getString("mother_age"));
                    txtMOTHER_ADDRESS.setText(rs.getString("mother_address"));
                    txtMOTHER_PHONE.setText(rs.getString("mother_phone_number"));
                    txtMOTHER_DOB.setText(rs.getString("mother_date_of_birth"));
                    txtMOTHER_OCCUPATION.setText(rs.getString("mother_occupation"));
                    txtEMERGENCY.setText(rs.getString("emergency_person"));
                    txtRELATIONSHIP.setText(rs.getString("relationship"));
                    txtEMERADD.setText(rs.getString("emergency_address"));
                    txtEMERPHONE.setText(rs.getString("emergency_phone"));
                    txtALTERNATE.setText(rs.getString("alternate"));
                    txtALTPHONE.setText(rs.getString("alternate_phone"));
                    
                    con.close();
                    
                } else {
                    JOptionPane.showMessageDialog(this, "No record found for Citizen ID: ");
                    txtUSERNAME.setText("");
                    txtPASSWORD.setText("");
                    txtFIRST.setText("");
                    txtMIDDLE.setText("");
                    txtLAST.setText("");
                    cmbSUFFIX.setText("");
                    txtAGE.setText("");
                    txtCURADD.setText("");
                    txtPERADD.setText("");
                    txtGENDER.setText("");
                    txtPHONE.setText("");
                    txtDOB.setText("");
                    cmbCIVIL_STATUS.setText("");
                    cmbNATIONALITY.setText("");
                    txtOCCUPATION.setText("");
                    txtRELIGION.setText("");
                    txtFATHER_NAME.setText("");
                    txtFATHER_AGE.setText("");
                    txtFATHER_ADDRESS.setText("");
                    txtFATHER_PHONE.setText("");
                    txtFATHER_DOB.setText("");
                    txtFATHER_OCCUPATION.setText("");
                    txtMOTHER_NAME.setText("");
                    txtMOTHER_AGE.setText("");
                    txtMOTHER_ADDRESS.setText("");
                    txtMOTHER_PHONE.setText("");
                    txtMOTHER_DOB.setText("");
                    txtMOTHER_OCCUPATION.setText("");
                    txtEMERGENCY.setText("");
                    txtRELATIONSHIP.setText("");
                    txtEMERADD.setText("");
                    txtEMERPHONE.setText("");
                    txtALTERNATE.setText("");
                    txtALTPHONE.setText("");
                        }
                }
            catch (SQLException e) {
               JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
               e.printStackTrace();
           } catch (ClassNotFoundException ex) {
               JOptionPane.showMessageDialog(this, "Driver Error: " + ex.getMessage());
               ex.printStackTrace();
           }
        
            if (!isRegistered.isRegistered) {
                    txtUSERNAME.setText("");
                    txtPASSWORD.setText("");
                    txtFIRST.setText("");
                    txtMIDDLE.setText("");
                    txtLAST.setText("");
                    cmbSUFFIX.setText("");
                    txtAGE.setText("");
                    txtCURADD.setText("");
                    txtPERADD.setText("");
                    txtGENDER.setText("");
                    txtPHONE.setText("");
                    txtDOB.setText("");
                    cmbCIVIL_STATUS.setText("");
                    cmbNATIONALITY.setText("");
                    txtOCCUPATION.setText("");
                    txtRELIGION.setText("");
                    txtFATHER_NAME.setText("");
                    txtFATHER_AGE.setText("");
                    txtFATHER_ADDRESS.setText("");
                    txtFATHER_PHONE.setText("");
                    txtFATHER_DOB.setText("");
                    txtFATHER_OCCUPATION.setText("");
                    txtMOTHER_NAME.setText("");
                    txtMOTHER_AGE.setText("");
                    txtMOTHER_ADDRESS.setText("");
                    txtMOTHER_PHONE.setText("");
                    txtMOTHER_DOB.setText("");
                    txtMOTHER_OCCUPATION.setText("");
                    txtEMERGENCY.setText("");
                    txtRELATIONSHIP.setText("");
                    txtEMERADD.setText("");
                    txtEMERPHONE.setText("");
                    txtALTERNATE.setText("");
                    txtALTPHONE.setText("");
            JOptionPane.showMessageDialog(null, "Please complete Personal Details registration first.");
                
             return;
        }
    }//GEN-LAST:event_btnREFRESHActionPerformed

    private void txtLASTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLASTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLASTActionPerformed

    private void btnCONFIRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCONFIRMActionPerformed
        if (!isRegistered.isRegistered) {
            JOptionPane.showMessageDialog(null, "Please complete Personal Details registration first.");
             return;
        }

        else {
        JOptionPane.showMessageDialog(this, "Thank you for registering! Proceeding to Home Page...");
        this.dispose();

        new LoginForm().setVisible(true);
                     }
    }//GEN-LAST:event_btnCONFIRMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCONFIRM;
    private javax.swing.JButton btnREFRESH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cmbCIVIL_STATUS;
    private javax.swing.JTextField cmbNATIONALITY;
    private javax.swing.JTextField cmbSUFFIX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField txtAGE;
    private javax.swing.JTextField txtALTERNATE;
    private javax.swing.JTextField txtALTPHONE;
    private javax.swing.JTextField txtCURADD;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEMERADD;
    private javax.swing.JTextField txtEMERGENCY;
    private javax.swing.JTextField txtEMERPHONE;
    private javax.swing.JTextField txtFATHER_ADDRESS;
    private javax.swing.JTextField txtFATHER_AGE;
    private javax.swing.JTextField txtFATHER_DOB;
    private javax.swing.JTextField txtFATHER_NAME;
    private javax.swing.JTextField txtFATHER_OCCUPATION;
    private javax.swing.JTextField txtFATHER_PHONE;
    private javax.swing.JTextField txtFIRST;
    private javax.swing.JTextField txtGENDER;
    private javax.swing.JTextField txtLAST;
    private javax.swing.JTextField txtMIDDLE;
    private javax.swing.JTextField txtMOTHER_ADDRESS;
    private javax.swing.JTextField txtMOTHER_AGE;
    private javax.swing.JTextField txtMOTHER_DOB;
    private javax.swing.JTextField txtMOTHER_NAME;
    private javax.swing.JTextField txtMOTHER_OCCUPATION;
    private javax.swing.JTextField txtMOTHER_PHONE;
    private javax.swing.JTextField txtOCCUPATION;
    private javax.swing.JPasswordField txtPASSWORD;
    private javax.swing.JTextField txtPERADD;
    private javax.swing.JTextField txtPHONE;
    private javax.swing.JTextField txtRELATIONSHIP;
    private javax.swing.JTextField txtRELIGION;
    private javax.swing.JTextField txtUSERNAME;
    // End of variables declaration//GEN-END:variables

    private void setExtendedState(int MAXIMIZED_BOTH) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
